// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC78iP_odpF1k0D4VvtWDtiEyZ0ADQOro8',
    appId: '1:702071822619:android:0512c6128328bb6d7ddbbe',
    messagingSenderId: '702071822619',
    projectId: 'flutterchat-1258f',
    storageBucket: 'flutterchat-1258f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOBXonRg_buw2UsQMX1g-2gU2qIoLV_KA',
    appId: '1:702071822619:ios:ffeeec99dbc2a55a7ddbbe',
    messagingSenderId: '702071822619',
    projectId: 'flutterchat-1258f',
    storageBucket: 'flutterchat-1258f.appspot.com',
    androidClientId: '702071822619-dimvf7lh1u7v37f32vpf65qahadgoh57.apps.googleusercontent.com',
    iosClientId: '702071822619-7qss4b0shivd3k6a3tgcqdlras7r5t73.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraDetection',
  );

}